# Generated by Django 2.1.1 on 2018-09-23 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linea', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDocumento', models.IntegerField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de extranjería'), ('PB', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('NI', 'NIT')], default=1)),
                ('NumeroDocumento', models.CharField(max_length=6)),
                ('PrimerApellido', models.CharField(max_length=35)),
                ('SegundoApellido', models.CharField(max_length=35)),
                ('PrimerNombre', models.CharField(max_length=35)),
                ('SegundoNombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1900)])),
                ('clase', models.IntegerField(choices=[(1, 'AUTOMÓVIL'), (2, 'BUS'), (3, 'BUSETA'), (4, ' CAMIÓN'), (5, 'CAMIONETA'), (6, 'CAMPERO'), (7, 'MICROBÚS'), (8, 'TRACTOCAMIÓN'), (9, 'MOTOCICLETA'), (10, 'MOTOCARRO'), (11, ' MOTOTRICICLO'), (12, 'CUATRIMOTO'), (13, 'VOLQUETA'), (14, 'OTRO')], default=1)),
                ('placa', models.CharField(max_length=6)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Color')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Linea')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Marca')),
            ],
        ),
        migrations.AddField(
            model_name='linea',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Marca'),
        ),
    ]
