# Generated by Django 2.1.1 on 2018-09-24 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_vehiculo_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.IntegerField(default=2018, validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
