# Generated by Django 2.1.1 on 2018-09-23 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Celular', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El formato del celular debe ser: '999-9999999'. maximo 10 digitos", regex='\\d{3}-\\d{7}-\\d')])),
                ('TipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de extranjería'), ('PB', 'Pasaporte'), ('TI', 'Tarjeta de identidad'), ('NI', 'NIT')], default='CC', max_length=2)),
                ('NumeroDocumento', models.CharField(max_length=6)),
                ('PrimerApellido', models.CharField(max_length=35)),
                ('SegundoApellido', models.CharField(max_length=35)),
                ('PrimerNombre', models.CharField(max_length=35)),
                ('SegundoNombre', models.CharField(max_length=35)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
            ],
        ),
    ]
