# Generated by Django 2.1.1 on 2018-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0002_auto_20180924_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='NumeroDocumento',
            field=models.CharField(max_length=12),
        ),
    ]
